module.exports = {
	// COMMON CODES
	CODE_SUCCESS: 'C000',
	CODE_NO_RESULT: 'C001',
	CODE_UNEXPECTED_ERROR: 'C002',
	CODE_INTERNAL_SERVER_ERROR: 'C003',
	CODE_TOKEN_INVALID: 'C004',
	CODE_NO_TOKEN_PROVIDED: 'C005',
	CODE_NO_PERMISSION: 'C006',
	CODE_MISSING_REQUIRED_PARAMETERS: 'C007',
	CODE_PARAM_NOT_CORRECT_FORMAT: 'C008',
	CODE_PARAM_CAN_NOT_ZERO: 'C009',
	CODE_UPLOAD_FILE_FAILED: 'C010',
	CODE_INVALID_FILE: 'C011',
};
