module.exports = {
	DAY: 'DAY',
	WEEK: 'WEEK',
	DAYWEEK: 'DAYWEEK',
	TOUR_COMMISSIONS_FOR_SYSTEM: 'TOUR_COMMISSIONS_FOR_SYSTEM',
	TOUR_COMMISSIONS_FOR_HOST_OWNER: 'TOUR_COMMISSIONS_FOR_HOST_OWNER',
	TOUR_BREAK_TIME_DURATION_IN_HOUR: 'TOUR_BREAK_TIME_DURATION_IN_HOUR',
	NUMBER_OF_DAYS_TO_BOOK_TOUR_IN_ADVANCED: 'NUMBER_OF_DAYS_TO_BOOK_TOUR_IN_ADVANCED',
	DEFAULT_USER_AVATAR: 'DEFAULT_USER_AVATAR',
};
