module.exports = {
	NUMBER_LIMIT_ACCOUNT: 100,
	SECOND_LIMIT_RESET_CODE: 900,
	SECOND_LIMIT_VERIFY_CODE: 900,
	LIST_LANGUAGE_SUPPORT: ['en', 'ja'],

	// SYSTEM SETTINGS
	NUMBER_OF_DAYS_TO_BOOK_TOUR_IN_ADVANCED: 3,
	TOUR_BREAK_TIME_DURATION_IN_HOUR: 2,

	// LEVEL
	LEVEL_ADMIN: 1,
	LEVEL_USER: 2,
	LEVEL_HOST: 3,

	// CATEGORY
	CATEGORY_OTHER: 1,

	// TRANSPORT
	TRANSPORT_OTHER: 1,

	// HOST REQUEST STATUS
	HOST_REQUEST_NONE: 0,
	HOST_REQUEST_REJECTED: 1,
	HOST_REQUEST_PENDING: 2,

	// TOUR STATUS
	TOUR_UNPUBLISHED: 0,
	TOUR_REJECTED: 1,
	TOUR_PUBLISHED: 2,

	// TOURS EDIT STATUS
	TOURS_EDIT_PENDING: 0,
	TOURS_EDIT_REJECTED: 1,
	TOURS_EDIT_APPROVED: 2,

	// ORDER STATUS
	ORDER_UNCONFIRMED: 0,
	ORDER_CONFIRMED: 1,
	ORDER_FINISHED: 2,

	// TRANSACTION TYPE
	TRANSACTION_TYPE_USER_PAYS_SYSTEM: 1,
	TRANSACTION_TYPE_SYSTEM_REFUNDS_TO_USER: 2,
	TRANSACTION_TYPE_SYSTEM_ALLOWS_HOST_TO_WITHDRAW_FOR_TOUR: 3,
	TRANSACTION_TYPE_SYSTEM_ALLOWS_HOST_TO_WITHDRAW_FOR_COMMISSION: 4,
	TRANSACTION_TYPE_HOST_WITHDRAW: 5,

	// TRANSACTION STATUS
	TRANSACTION_STATUS_PENDING: 0,
	TRANSACTION_STATUS_SUCCEEDED: 1,
	TRANSACTION_STATUS_FAILED: 2,
	TRANSACTION_STATUS_UNCLAIMED: 3,
};
